### PR TITLE
update rubbgy version and add missing dependencies

### PR DESCRIPTION
**Pull request by pierrejego**
link to georchestra/georchestra.github.io/issues/#105

as https://github.com/georchestra/georchestra.github.io/pull/91 I am not sure it will fix it. 
Need to test via travis

### CODE REVIEW

**Comment by pierrejego** [comment]
How can I test this PR in travis ? I don't have enough right to create a branch here.

**Comment by fvanderbiest** [comment]
> How can I test this PR in travis ? I don't have enough right to create a branch here.

You're now part of the core team, you should have the rights to.
\o/

**Comment by pierrejego** [comment]
Thanks !

**Comment by pierrejego** [comment]
Migration to be done on gitaction. End of service of travis.org

**Pull request closed without merging**
