### PR TITLE
fixing travis build

### PR DESCRIPTION
**Pull request by RemiDesgrange**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Removing htmlproofer does not fix the issues ;-)

**Comment by RemiDesgrange** [comment]
The build is pending but in reallity, it's green. What do you mean by "Removing htmlproofer does not fix the issues". Does it mean that I should remove broken link and keep using htmlproofer ?

**Comment by fvanderbiest** [comment]
> Does it mean that I should remove broken link and keep using htmlproofer ?

That's the original idea with using htmlproofer indeed.
But indeed, if it represents too much work, it might be reconsidered.

**Comment by jeanpommier** [comment]
htmlproofer ./_site
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html... 


Checking 329 external links...
Ran on 105 files!


- ./_site/blog.html
  *  internally linking to /blog/2019/03/25/geocom-2019-en/, which does not exist (line 0)
     <a href="/blog/2019/03/25/geocom-2019-en/">Read further.</a>
- ./_site/blog/2010/10/01/openstreetmap-et-ids/index.html
  *  External link http://blog.geoserver.org/2009/01/30/geoserver-and-openstreetmap/ failed: 500 No error
- ./_site/blog/2011/12/17/pigma-nouvelle-plateforme-georchestra/index.html
  *  External link http://blog.geoserver.org/2011/10/07/geoserver-2-1-2-release/ failed: 500 No error
- ./_site/blog/2012/06/12/zoom-sur-l-explorateur-de-catalogue/index.html
  *  External link http://blog.georchestra.org/public/mapfishapp-cswbrowser.png failed: 503 No error
- ./_site/blog/2012/12/16/georchestra-12.11-bolivia-is-out/index.html
  *  External link https://github.com/georchestra/georchestra/archive/12.11.tar.gz failed: 404 No error
- ./_site/blog/2013/03/24/georchestra-community-meeting-rennes/index.html
  *  External link http://www.agrocampus-ouest.fr/infoglueDeliverLive/footer/plans-acces/rocade-rennes failed: 404 No error
  *  External link http://www.breizhgo.com/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
  *  External link http://www.rennes.aeroport.fr/Tous-les-vols/Vols-directs failed: 404 No error
  *  External link http://www.sejours-affaires.com/residence-hoteliere-aparthotel-rennes-191.html failed: got a time out (response code 0)
- ./_site/blog/2013/10/02/georchestra-release-13.09/index.html
  *  External link http://www.ohloh.net/p/georchestra failed: 301 SSL connect error
  *  External link https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md failed: 429 No error
- ./_site/blog/2014/07/09/actualiza-a-geoserver-2.5.1/index.html
  *  External link http://www.camptocamp.com/geospatial/ failed: 404 No error
- ./_site/blog/2014/07/10/version-14.06/index.html
  *  External link https://github.com/georchestra/georchestra/blob/14.06/README.md failed: 429 No error
  *  External link https://github.com/georchestra/georchestra/blob/14.06/RELEASE_NOTES.md failed: 429 No error
- ./_site/blog/2015/01/30/georchestra-14.12-is-available/index.html
  *  External link https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md#version-1412-stable-version failed: 429 No error
- ./_site/blog/2015/04/06/codesprint-a-beg-meil/index.html
  *  External link http://plan.kwiqlink.com/WERJO6BUMZ7907UV failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/blog/2015/07/01/geocom2015-compte-rendu/index.html
  *  External link https://storify.com/fvanderbiest/geocom-2015-strasbourg failed: 403 No error
- ./_site/blog/2016/03/05/georchestra-15.12-fr/index.html
  *  External link https://build.georchestra.org/ci/job/georchestra-generic-wars/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
- ./_site/blog/2017/11/26/code-sprint-sos-fr/index.html
  *  External link https://www.constellation-sdi.org/fr/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/blog/2019/06/12/geocom-2019-en/index.html
  *  External link https://www.lepuyenvelay-tourisme.fr/manifestations-puy-en-velay/congres-geocom/ failed: 404 No error
  *  internally linking to /blog/2019/03/25/geocom-2019-en/, which does not exist (line 0)
     <a href="/blog/2019/03/25/geocom-2019-en/">Read further.</a>
- ./_site/blog/2019/06/12/geocom-2019-fr/index.html
  *  internally linking to /blog/2019/03/25/geocom-2019-fr/, which does not exist (line 0)
     <a href="/blog/2019/03/25/geocom-2019-fr/">Lire la suite</a>
- ./_site/blog/2020/01/28/geocom-2020-en/index.html
  *  internally linking to TODO, which does not exist (line 0)
     <a href="TODO">this form</a>
- ./_site/blog/2020/01/28/geocom-2020-fr/index.html
  *  External link http://hotel-de-perros.fr/ failed: got a time out (response code 0)
  *  External link https://www.hotel-les-bains-perros-guirec.fr/fr/ failed: got a time out (response code 0)
  *  internally linking to TODO, which does not exist (line 0)
     <a href="TODO">ce formulaire</a>
- ./_site/documentation.html
  *  External link https://www.geonetwork-opensource.org/manuals/3.4.x/en/ failed: 404 No error
- ./_site/es/blog.html
  *  External link https://github.com/georchestra/georchestra/blob/15.06/.travis.yml failed: 429 No error
- ./_site/es/comunidad.html
  *  External link http://geofao.org.bo/ failed: got a time out (response code 0)
  *  External link http://www.sisyphe.upmc.fr/ failed: got a time out (response code 0)
  *  External link http://www6.rennes.inra.fr/umrsas/ failed: 302 SSL connect error
  *  External link https://www.cigalsace.org/portail/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
  *  External link https://www6.nancy.inra.fr/eef/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
- ./_site/es/documentacion.html
  *  External link http://geowebcache.org/docs/1.8.1/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
  *  External link https://www.geonetwork-opensource.org/manuals/3.4.x/es/ failed: 404 No error
- ./_site/fr/blog.html
  *  External link http://blog.geoserver.org/2011/12/21/geoserver-2-1-3-released/ failed: 500 No error
  *  External link http://hudson-ci.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Failure when receiving data from the peer
  *  External link http://www.afigeo.asso.fr/documentation/publications.html?download=512%3Aafigeo-programme_journee_ig_opendata_06062012 failed: 404 No error
  *  External link http://www.craig.fr/content/inscription-au-georchestra-community-meeting-clermont-ferrand-19-et-20-juin-2014 failed: 404 No error
  *  External link http://www.craig.fr/reunions/1229-georchestra-community-meeting failed: 404 No error
  *  External link http://www.geoconnections.org/fr/communities/developers/standards/web_processing_service failed: got a time out (response code 0)
  *  internally linking to /blog/2019/03/25/geocom-2019-fr/, which does not exist (line 0)
     <a href="/blog/2019/03/25/geocom-2019-fr/">Lire la suite</a>
- ./_site/fr/documentation.html
  *  External link https://www.geonetwork-opensource.org/manuals/3.4.x/fr/ failed: 404 No error
- ./_site/software.html
  *  External link http://geowebcache.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
  *  External link https://github.com/georchestra/geonetwork/blob/georchestra-gn3-3.0.x/README.md failed: 429 No error
  *  External link https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md#version-1302 failed: 429 No error
  *  External link https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md#version-1306 failed: 429 No error
htmlproofer 3.15.3 | Error:  HTML-Proofer found 47 failures!

**Comment by pierrejego** [comment]
Travis is not used anymore, I close this issue.

**Pull request closed without merging**
